src/AtosLibrary.WebHost/Pages/CreateReader.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AtosLibrary.Application.Features.RegistrationReader;
using AtosLibrary.Application.Infrastructure;
using AtosLibrary.Presentation.Reader;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AtosLibrary.WebHost
{
    public class CreateReaderModel : PageModel
    {
        private readonly ICommandHandler<RegistrationReaderCommand> _commandHandler;

        public CreateReaderModel(ICommandHandler<RegistrationReaderCommand> commandHandler)
        {
            _commandHandler = commandHandler;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public ReaderModel ReaderModel { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _commandHandler.Handle(new RegistrationReaderCommand(ReaderModel.Name, ReaderModel.Surname, ReaderModel.Country, ReaderModel.City));

            return RedirectToPage("/ReaderIndex");
        }
    }
}

src/AtosLibrary.WebHost/Pages/EditReader.cshtml.cs
using System;
using AtosLibrary.Application.Features.EditReader;
using AtosLibrary.Application.Infrastructure;
using AtosLibrary.Presentation.Reader;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AtosLibrary.WebHost
{
    public class EditReaderModel : PageModel
    {
        private readonly IReaderPresentationRepository _readerPresentationRepository;
        private readonly ICommandHandler<EditReaderCommand> _commandHandler;

        public EditReaderModel(IReaderPresentationRepository readerPresentationRepository, ICommandHandler<EditReaderCommand> commandHandler)
        {
            _readerPresentationRepository = readerPresentationRepository;
            _commandHandler = commandHandler;
        }

        public void OnGet(Guid id)
        {
            ReaderModel = _readerPresentationRepository.Get(id);
        }

        [BindProperty]
        public ReaderModel ReaderModel { get; set; }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _commandHandler.Handle(new EditReaderCommand(ReaderModel.Id, ReaderModel.Name, ReaderModel.Surname, ReaderModel.Country, ReaderModel.City));

            return RedirectToPage("/ReaderIndex");
        }
        
    }
}

src/AtosLibrary.WebHost/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AtosLibrary.WebHost.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

src/AtosLibrary.WebHost/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AtosLibrary.WebHost.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

src/AtosLibrary.WebHost/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace AtosLibrary.WebHost.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

src/AtosLibrary.WebHost/Pages/ReaderIndex.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AtosLibrary.Application.Features.DeleteReader;
using AtosLibrary.Application.Features.EditReader;
using AtosLibrary.Application.Infrastructure;
using AtosLibrary.Presentation.Reader;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AtosLibrary.WebHost
{
    public class ReaderIndexModel : PageModel
    {
        private readonly IReaderPresentationRepository _presentationRepository;
        private readonly ICommandHandler<DeleteReaderCommand> _commandHandler;

        public ReaderIndexModel(IReaderPresentationRepository presentationRepository, ICommandHandler<DeleteReaderCommand> commandHandler)
        {
            _presentationRepository = presentationRepository;
            _commandHandler = commandHandler;
        }

        public IList<ReaderModel> Readers { get; set; }

        [BindProperty]
        public string SearchText { get; set; }

        public void OnGet(string SearchText)
        {
            if (SearchText is null)
                Readers = _presentationRepository.GetList().ToList();
            else
                Readers = _presentationRepository.GetBySurname(SearchText).ToList();
        }

        public IActionResult OnPostDelete(Guid id)
        {
            _commandHandler.Handle(new DeleteReaderCommand(id));

            return RedirectToPage("/ReaderIndex", new { SearchText });
        }

        public IActionResult OnPostSearch()
        {
            return RedirectToPage("/ReaderIndex", new { SearchText });
        }
    }
}

src/AtosLibrary.WebHost/Pages/CreateReader.cshtml
@page
@model AtosLibrary.WebHost.CreateReaderModel
@{
    ViewData["Title"] = "CreateReader";
}

<h1>CreateReader</h1>

<form method="post">
    Name: <input asp-for="ReaderModel.Name"/><br/>
    Surname: <input asp-for="ReaderModel.Surname"/><br />
    Country: <input asp-for="ReaderModel.Country"/><br />
    City: <input asp-for="ReaderModel.City"/><br />
    <input type="submit"/>
</form>

src/AtosLibrary.WebHost/Pages/EditReader.cshtml
@page "Guid:Id"
@model AtosLibrary.WebHost.EditReaderModel
@{
    ViewData["Title"] = "EditReader";
}

<h1>EditReader</h1>


<form method="post">
    <input type="hidden" asp-for="ReaderModel.Id" />
    Name: <input asp-for="ReaderModel.Name" /><br />
    Surname: <input asp-for="ReaderModel.Surname" /><br />
    Country: <input asp-for="ReaderModel.Country" /><br />
    City: <input asp-for="ReaderModel.City" /><br />
    <input type="submit" />
</form>

src/AtosLibrary.WebHost/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/AtosLibrary.WebHost/Pages/ReaderIndex.cshtml
@page "string:SearchText"

@model AtosLibrary.WebHost.ReaderIndexModel
@{
    ViewData["Title"] = "ReaderIndex";
}

<h1>ReaderIndex</h1>

<form asp-page-handler="Search" method="post">
    Search by surname: <input asp-for="SearchText" />
    <button type="submit">search</button>
</form>

<form method="post">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Surname</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var contact in Model.Readers)
            {
            <tr>
                <td>@contact.Id  </td>
                <td>@contact.Name</td>
                <td>@contact.Surname</td>
                <td>
                    <a asp-page="./EditReader" asp-route-id="@contact.Id">Edit</a> |
                    <button type="submit" asp-page-handler="delete" asp-route-id="@contact.Id">delete</button>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <a asp-page="/CreateReader">Create New</a>
</form>

src/AtosLibrary.WebHost/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AtosLibrary.WebHost</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AtosLibrary.WebHost</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/CreateReader">Create reader</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/ReaderIndex">Reader Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AtosLibrary.WebHost - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>